name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  # Build and Push Docker Images to DockerHub
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub using GitHub secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the `web` image
      - name: Build and push web image
        run: |
          docker build -t vaishnavpuzhakkal/my-repo:root-web -f Dockerfile.web .
          docker push vaishnavpuzhakkal/my-repo:root-web

      # Build and push the `db` image
      - name: Build and push db image
        run: |
          docker build -t vaishnavpuzhakkal/my-repo:postgres -f Dockerfile.db .
          docker push vaishnavpuzhakkal/my-repo:postgres

  # Deploy the Docker Compose setup on EC2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SSH into the EC2 instance and deploy
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            # Navigate to the directory containing the Docker Compose file
            cd /home/ubuntu

            # Pull the latest images from DockerHub
            docker pull vaishnavpuzhakkal/my-repo:root-web
            docker pull vaishnavpuzhakkal/my-repo:postgres
            
            # Restart Docker containers with the updated images
            docker-compose down
            docker-compose up -d

            # Reload Nginx to apply any configuration changes
            sudo systemctl reload nginx
