# Generated by Django 5.1.4 on 2025-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_remove_message_sender_chatsession_message_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='Demo', max_length=50),
        ),
    ]
