# Generated by Django 5.1.4 on 2025-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_content_heading_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_content',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
