name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'Backend/**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build web image with daphne
      - name: Build and push web image
        run: |
          docker build --no-cache -t vaishnavpuzhakkal/my-repo:root-web -f ./Backend/Root/Dockerfile .
          docker push vaishnavpuzhakkal/my-repo:root-web
          docker push vaishnavpuzhakkal/my-repo:root-web

      # Build postgres image if needed
      - name: Build and push db image
        run: |
          docker build -t vaishnavpuzhakkal/my-repo:postgres -f ./Backend/Root/Dockerfile .
          docker push vaishnavpuzhakkal/my-repo:postgres

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ubuntu           # Confirmed correct
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu         # Confirmed correct path
            pwd                     # Debug: print working directory
            ls -la                  # Debug: list files
            docker pull vaishnavpuzhakkal/my-repo:root-web
            docker pull vaishnavpuzhakkal/my-repo:postgres
            docker-compose down
            docker-compose up -d
            docker ps
            docker logs root-web-1 --tail=50